hfg-gmuend/openmoji

src/flags/subdivision-flag/1F3F4-E0067-E0062-E0073-E0063-E0074-E007F.svg

Fix diagonal line on Scottish flag

---

src/flags/subdivision-flag/1F3F4-E0067-E0062-E0073-E0063-E0074-E007F.svg

In response to [this comment](https://github.com/hfg-gmuend/openmoji/commit/fd6c5178fa08ec7d9a8e854a7ab4ab6aee50f04d#commitcomment-35474244)

Fix width of diagonals on Scottish Flag

---

src/travel-places/sky-weather/1F31A.svg
src/travel-places/sky-weather/1F31D.svg

Standardise moon emojis and adjust smile

---

src/smileys-emotion/face-smiling/1F601.svg

Fix Beaming Face

---

changelog.txt
src/flags/country-flag/1F1F8-1F1E8.svg

#72 
Not failing because of my changes

Fix Seychelles flag

---

src/people-body/person-symbol/1F463.svg

#72 
@dnlutz thoughts? before isn't even recognisably feet

Improve feet

---

src/flags/country-flag/1F1F2-1F1F7.svg
src/flags/country-flag/1F1F5-1F1FC.svg

Flag fixes

---

changelog.txt
src/smileys-emotion/face-concerned/1F616.svg

#105 
https://emojipedia.org/confounded-face/
think this works, but can be improved

Fix confounded face to be more consistent

---

changelog.txt
src/travel-places/sky-weather/2603.svg
src/travel-places/sky-weather/26C4.svg

Wanna make sure that I've made the right choice here

Standardise snowmen

---

changelog.txt
src/symbols/zodiac/2648.svg
src/symbols/zodiac/264A.svg
src/symbols/zodiac/264D.svg
src/symbols/zodiac/264E.svg
src/symbols/zodiac/264F.svg
src/symbols/zodiac/2650.svg
src/symbols/zodiac/2651.svg

Fix zodiac signs

---

.github/workflows/test-pull-request.yml
helpers/create-zip.sh
helpers/export-emojipedia.sh
helpers/export-pdf.sh
helpers/export-png.sh
helpers/export-svg.sh
helpers/export-zip.sh
helpers/generate-fonts.sh
helpers/generate.sh
package.json

This change is a review of all the helper scripts to apply some bash best practices and get them passing the shellcheck linter. This change adds a github CI step to verify that the scripts pass shellcheck, and a package script for running shellcheck manually, though this requires `shellcheck` installed on the system.

Scripts review

---

src/symbols/av-symbol/23FA.svg

record button circle should have the deeper red

---

API.md
index.js
package.json
test/module-index.js

Data access API for OpenMoji npm module

---

helpers/export-png.sh
helpers/export-svg.sh
helpers/lib/export-png.sh
helpers/lib/export-svg-black.js
helpers/lib/export-svg-color.sh
helpers/lib/export-svg-skintones.js
helpers/lib/export-svg-skintones.sh
package.json

This change addresses issues raised in #220, discovered in #219, with the build system.  These are a few small but significant defects.
The change also introduces new cache-clear scripts for convenience.

Fix build system bugs

---

changelog.txt
src/smileys-emotion/face-unwell/1F637.svg

with corona and all I feel like it should be slightly more detailed/realistic

Make mask more realistic

---

data/enhancements-emoji-unicode-data.csv
data/openmoji.csv
data/openmoji.json

since I created that from scratch in #218
I think i added it to `data/openmoji.csv` back then.

fixed attribution

---

src/extras-openmoji/objects/E151.svg

i just figured the white background shouldn't go on top:

fixed wrong stacking for white background

---

README.md

Add link in README.md to JavaFXEmojiTextFlow library that helps to use Openmoji in JavaFX UI based applications

Openmoji in JavaFX UI -> Update README.md

---

README.md

see rendered markdown here: https://github.com/jjb/openmoji/tree/patch-1#downloads--distribution-channels

add CDN to distribution/usage methods

---

package-lock.json
package.json
test/ttf.mjs

This checks for the bug reported in #438, and should help prove the fix in #458.

Add tests to check TTFs have expected tables

---

src/extras-unicode/subdivision-flag/1F3F4-E0061-E0076-E007F.svg

@b-g Added improvements 
```
varia@varia:~/Desktop/my_code_projects/openmoji$ npm run test-dev
> openmoji@15.0.0 test-dev
> mocha --parallel --reporter min --invert --grep "production" test/*.{js,mjs} --openmoji-data-json $PWD/data/openmoji.json --openmoji-src-folder $PWD/src
55943 passing (53s)
varia@varia:~/Desktop/my_code_projects/openmoji$ 
```

Update Alabama flag SVG

---

data/enhancements-emoji-unicode-data.csv
data/openmoji.csv
data/openmoji.json
src/flags/country-flag/1F1F2-1F1F6.svg

Updated martinique flag emoji
Closes https://github.com/hfg-gmuend/openmoji/issues/517

Updated Martinique flag

---

font/README.md

Here's a recipe to use the font via jsdelivr.com
(If you like the general idea) These docs could live here, or somewhere else, or maybe be integrated into the generate-font-demo script.

easy font usage via jsdelivr.com
