hfg-gmuend/openmoji

- test/file-format.js
- test/utils/utils.js
Can't use the JSDOM version of the svg as it trims duplicate attributes, so I added a utility function to read the file to a string. Have to regex for the elements and then regex for the attributes. All existing emoji pass these tests
Test required due to #74
> Add test for duplicate attributes

- COPYING-code.txt
- COPYING-graphics.txt
- COPYING.LESSER-code.txt
OpenMoji is being packaged as an RPM for the Fedora Project. The following page has more details:
https://bugzilla.redhat.com/show_bug.cgi?id=1803059
However, the distribution archive does not seem to include a copy of the full texts of the licenses under which it is distributed.
In general we like to include a copy of the license for programs we package, for the following reasons:
* it is useful to other users who might download a tarball of your package to be able to have a copy of the license at hand.
* it ensures that the license is available offline
* it ensures that there is no ambiguity about the license
Although we could retrieve the source text from an alternate location and include that, this makes it more difficult to track changes you may make to the licensing in future and …
> Include licence text.

- changelog.txt
- helpers/README.md
- helpers/prettyfy-figma-svg.js
refs #196 , @b-g
1. open this file in figma:  
[https://www.figma.com/file/sZZLEmdnMTOAxq0mTgO4WN/new-openmoji?node-id=169%3A0](new-openmoji.figma)
2. export the frame using these settings:  
3. choose any directory in `./src`
4. run `node helpers/prettyfy-figma-svg.js`
1. running `node helpers/prettyfy-figma-svg.js` should remove the `.figma` interfix.
2. The following changes should have been applied to the svg:
1. remove `fill="none"` attribute from the svg element. Elements without fill should have a `fill="none"` attribute.
2. no element should have a figma default id (like `Rectangle 4`,  `Vector 7` etc…)
3. remove root `<g>` element
> initial commit figma cleanup script

- font/scfbuild-black.yml
- font/scfbuild-color.yml
It’s [strongly recommended][1] that `subfamily` be one of the four basic
styles, “regular”, “italic”, “bold”, “bold italic”.  Hence, “Color” and
“Black” should be part of the `family`, not the `subfamily`.
[1]: https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids
> Standardise subfamily names

- src/flags/country-flag/1F1F9-1F1FC.svg
Fixing Taiwanese flag 🇹🇼 `1F1F9-1F1FC` as mentioned in issue hfg-gmuend#150
> Changes needed 
> — make the sun bigger
> — _(potentially)_ separating out the rays from the core; might mean making the core smaller than official to allow for the rays to split out and align with the OpenMoji style... will have to play around with that
| OpenMoji v12.3.0 | Proposed | Official |
| ------ | ------ | ------ |
| <img width="200" src="https://raw.githubusercontent.com/hfg-gmuend/openmoji/dab906e9fc301673044ff18c58f791fec3372f18/src/flags/country-flag/1F1F9-1F1FC.svg"> | <img width="200" src="https://raw.githubusercontent.com/wayne-shih/HfG-OpenMoji/ws/%F0%9F%87%B9%F0%9F%87%BC1F1F9-1F1FC/src/flags/country-flag/1F1F9-1F1FC.svg"> | <img width="160" …
> fix(🇹🇼): white sun and rays

- src/flags/country-flag/1F1F2-1F1FF.svg
Fixing Mozambique flag 🇲🇿 `1F1F2-1F1FF` as mentioned in issue hfg-gmuend#150
> Mozambique: Add a yellow star.
Also added a white isosceles trapezoid to reflect an open book on the official flag
| OpenMoji v12.3.0 | Proposed | Official |
| ------ | ------ | ------ |
| <img width="200" src="https://raw.githubusercontent.com/hfg-gmuend/openmoji/dab906e9fc301673044ff18c58f791fec3372f18/src/flags/country-flag/1F1F2-1F1FF.svg"> | <img width="200" src="https://raw.githubusercontent.com/wayne-shih/HfG-OpenMoji/ws/%F0%9F%87%B2%F0%9F%87%BF1F1F2-1F1FF/src/flags/country-flag/1F1F2-1F1FF.svg"> | <img width="160" src="https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg"> |
> fix(🇲🇿): add yellow star, white book

- data/extras-unicode.csv
- data/openmoji.csv
- data/openmoji.json
- src/extras-unicode/subdivision-flag/1F3F4-E0064-E0065-E0062-E0079-E007F.svg
From the commit message:
> TODO: b/w generates an empty frame. The result should be either solid black lozenges or, which would be heraldically better, vertically striped ones.
> 
> The official blue is #008DC9. The emoji uses the closest approximation from the OpenMoji color palette, #61B2E4. The tester app shows all tests green.
I’ve tried to align this submission closely to [the one adding the Berlin flag](https://github.com/hfg-gmuend/openmoji/pull/198).
The source for the official color specification is https://www.km.bayern.de/download/10702_anlage_4a_manual_cd.pdf .
Re: b/w: Is there a possibility to have a hidden element in the `line` layer, that can be unveiled by the `helpers/lib/export-svg-black.js` script? Or would it be better, if I provided a dedicated black-white emoji …
> add subdivision flag de-by, Bavaria

- .editorconfig
[EditorConfig](https://editorconfig.org/) is a standard for configuring indentation styles (amongst other things).  It is supported by many different text editors.
The config file added by this commit will tell supporting editors to use two spaces for indentation (except in HTML files, where four spaces will be used).  This matches the existing practice of the OpenMoji project.
> Add an EditorConfig config

- README.md
The argument to `git clone` should be `--depth`.
> Fix typo in git clone instructions

- README.md
Hello,
I've created a library of CSS Classes based on twemoji-amazing and Font Awesome. This adds classes like `<i class="oma oma-face-with-monocle"></i>` to use Openmoji on your website.
By default, the files are distributed via the JSDeliver CDN, but this can be changed easily and the classes can be regenerated to accommodate any needs (like local hosting if needed).
I've added this library to the Community Extensions sections of the README.
> Add Openmoji Awesome to the community extensions

- src/flags/country-flag/1F1E7-1F1F3.svg
Hello,
I made some tests on the Brunei flag and I would like to suggest these design changes. The main problem I see is that the original flag dons a crescent, which is a religious symbol that many other flags have, and it seems to be the only one that somehow got lost in the simplification. Here is a summary of what I changed:
- bend the vertical side lines to better suggest hands
- break the circle apart to make the lower part look more like a crescent (which it is)
- bend the top horizontal line to make it look less like a cross (it is an umbrella)
I am not a skilled designer and I don’t feel strongly about this particular design, it’s mostly here to illustrate the point.
For reference, here is the actual flag and a before/after comparison:
> Minor design changes to the Brunei flag.

- src/flags/country-flag/1F1EB-1F1F0.svg
There is an almost unnoticeable issue with the emblem on the Malvinas flag, where the inner wavy stroke creates a small bulge on the edge of the emblem. This does not happen with all renderers and depends on the display resolution, so it’s really, really minor, but here it is in Chrome:
It happens because the tip of the stroke (highlighted in green) coincides with the edge of the emblem:
So I suggest trimming the edges of these strokes:
> Tweak Malvinas flag

- src/flags/country-flag/1F1F8-1F1F8.svg
Contrary to all the other flags I know, the star in the [flag of South Sudan](https://en.wikipedia.org/wiki/Flag_of_South_Sudan) points left instead of up. Unfortunately I could not find any information on why it is so.
> Fix South Sudan flag star orientation.

- src/flags/country-flag/1F1F9-1F1F1.svg
Note: this PR also tweaks the star position so that its barycenter lies at `y=36` (it was slightly offset at `36.503` previously).
Here is a before/after picture with the orientation highlighted:
The Constitution of the Democratic Republic of East Timor indicates that the star should point to the top left hand corner. I found a [construction sheet](https://www.fotw.info/flags/tl%27uno.html) illustrating that:
> Fix East Timor flag star orientation.

- src/food-drink/dishware/1F944.svg
- src/symbols/arrow/2194.svg
- src/symbols/arrow/2195.svg
- src/symbols/arrow/2196.svg
- src/symbols/arrow/2197.svg
- src/symbols/arrow/2198.svg
- src/symbols/arrow/2199.svg
- src/symbols/arrow/27A1.svg
- src/symbols/arrow/2934.svg
- src/symbols/arrow/2935.svg
- src/symbols/arrow/2B05.svg
- src/symbols/arrow/2B06.svg
- src/symbols/arrow/2B07.svg
- src/symbols/av-symbol/1F53C.svg
- src/symbols/av-symbol/1F53D.svg
Some of the SVG files have multiple elements with the same id.
This violates the specifications for the SVG format, and caused problems when I was trying to parse the files with another program.
Comparing these files to the other SVG sources for OpenMoji, I found that these id attributes are nonstandard.
Most of the SVG files have descriptive ids for each group ("line", "color", "skin", etc.), but not for the elements within those groups.
As such, the easiest fix was to simply remove those problematic id attributes.
Additionally, each of these duplicate id attributes have a form similar to `id="_x2935__xFE0F__1_"`.
While scanning the files,  I also found two av-symbol SVG files which had this form of id, but without the duplication.
Although these two files don't violate the …
> Remove problematic id attributes from certain SVG elements.

- FAQ.md
I just found a problem in the JavaScript implementation:
Emojis like 👩‍⚕️ have two parts: 👩 +⚕️.
But the current JavaScript implementation takes only the first codePoint into account.
The new implementation will take care of both cases: Single character emojies and double character emojis.
```
code = [...emoji].map(e => e.codePointAt(0).toString(16)).join(`-`)
```
The python implementation works fine though.
Follow up to #397, @b-g .
> FAQ: Better javascript implementation to also support emojis like 👩‍⚕️

- data/extras-openmoji.csv
- data/openmoji.csv
- data/openmoji.json
- index-list.html
This is the last remaining instance of a trailing comma, which was not captured in #388.
> Fix the last instance of a trailing comma

- color/svg/2622.svg
I noticed that the radiation symbol in openmoji is upside down, especially when [compared to other emoji sets](https://emojipedia.org/radioactive/), and the ANSI spec of it.
This should flip it over
> Flipping the symbol for ionising radiation to correct orientation

- data/extras-unicode.csv
- Unquote values in the `annotation` column, which are simple strings, not lists
- Quote values in the `openmoji_tags` column, which are lists, by definition
Both of these changes were applied to lines that deviated from the existing quoting pattern, so what's being done here is merely normalizing the quoting that is already applied in this file.
> Normalize quoting of fields in extras-unicode.csv

- data/extras-openmoji.csv
The `annotation` field was set to "return, back button", and the `openmoji_tags` was empty.
Typically the `annotation` field is not a comma-separated list, but a simple string, so it was changed to be simply "return" (which aligns with the other ui-element entries below, such as "close", "duplicate", "forward", etc.) and "back button" was moved to the `openmoji_tags` field.
> Split `annotation` and `openmoji_tags` for E24D in extras-openmoji.csv

- FAQ.md
Don't merge yet, it's only a draft pull request.
Attempt to solve  #404.
@Joshix-1 can you have a look at this?
It's not yet a working solution, because sometimes this character is needed:
🦴 -> "1F9B4", can be found in https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/72x72/1F9B4.png
🐿️ -> "1F43F-FE0F" , can be found in https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/72x72/1F43F.png
👩‍⚕️ -> "1F469-200D-2695-FE0F" can be found in https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/72x72/1F469-200D-2695-FE0F.png
Currently, the last example would break, because the FE0F should not be removed.
I think a distinction of cases is needed here. Am I right in the assumption, that all emojis that have more than two of these character sequences …
> FAQ: Better handeling of unicode value U+FE0F  with Python+Javascript.

- README.md
PR with the proposal to add a link inside the community extension section for the flutter library flutter_openmoji created by myself .
> Add a link to flutter_openmoji inside the community extension section

- data/enhancements-emoji-unicode-data.csv
- data/openmoji.csv
- data/openmoji.json
- index-list.html
- Remove redundant openmoji_tags that are already present in emojibase
- Add 'fingers' and 'star trek' as openmoji_tags
> Adjust tags of Vulcan salute emoji (U+1F596)

- font/README.md
There's two parts to this:
As I understand it, COLRv1 offers two advantages over COLRv0:
- Gradients (which are something that Openmoji doesn’t use).
- More reuse of elements, leading to potentially smaller file sizes.
The COLRv1 TTF file is indeed smaller.  However, for some reason the WOFF2 file is not:
| Size    | Filename                         |
| ------- | -------------------------------- |
| 2436372 | OpenMoji-color-glyf_colr_0.ttf   |
|  905144 | OpenMoji-color-glyf_colr_0.woff2 |
| 2220984 | OpenMoji-color-glyf_colr_1.ttf   |
|  972648 | OpenMoji-color-glyf_colr_1.woff2 |
Hence, I don’t think there’s any reason to recommend COLRv1 WOFF2 at the current time.
COLRv0 is the built-in format for colour fonts in Windows 10, so I don’t think it’s fair to say that it has very little …
> Font format recommendations

- FAQ.md
Hey, I noticed a few typos in the FAQ while reading it. I did not open an issue for though, I hope that's okay :)
I also changed the filenames, so that they get the monospaced font when rendered. Feel free to tell me to undo that if that's preferred.
> FAQ.md: fix several typos

- src/travel-places/time/1F567.svg
Make the short hand point between twelve and one in the twelve-thirty emoji.
On [the Emojipedia page for the twelve-thirty emoji](https://emojipedia.org/twelve-thirty#designs) we can see that some designs do this, while some point straight up at the twelve.
Here's what the suggested version looks like:
Fixes #423
> 1F567: short hand between twelve and one

- README.md
Link to Sticker packs for Telegram does not exist anymore. The user neither. Googling for that sticker pack gave no results. So I've removed the link.
PS: I hope it's okay to have no issue created first as this seems pretty easy..
> Update README.md: Removed link for Sticker Packs as it leads to a 404.

- font/README.md
- helpers/generate-fonts.sh
This should be done when building TTFs for release, so that the new fonts can be committed before the Git tag is created.
Provides a way to prevent recurrences of #485.
> Provide a way to specify the version of TTFs

- changelog.txt
- package-lock.json
- package.json
Thanks for this delightful emoji set!
This error blocks new developers from using any helper scripts. It seems this dependency's release was deleted and the maintainers no longer support the `.7` patch: https://github.com/libxmljs/libxmljs/issues/582#issuecomment-1117540543
```
~/_code/hfg-gmuend/openmoji 🌿 git status
On branch master
Your branch is up to date with 'upstream/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
...[irrelevant]...
nothing added to commit but untracked files present (use "git add" to track)
~/_code/hfg-gmuend/openmoji 🌿 nvm use
Found '/home/jan/_code/hfg-gmuend/openmoji/.nvmrc' with version <v14.16.1>
Now using node v14.16.1 (npm v6.14.12)
~/_code/hfg-gmuend/openmoji 🌿 npm install
> libxmljs@0.19.7 install …
```
> Fix libxmljs 404s by bumping patch version
